# Utiliser l'image officielle Node.js
FROM node:20-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers
COPY . .

# Construire l'application React
RUN npm run build

# Installer un serveur léger pour servir l'application
RUN npm install -g serve

# Exposer le port
EXPOSE 3000

# Démarrer le serveur pour servir l'application construite
CMD ["serve", "-s", "build", "-l", "3000"]
